sudo: false
language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
before_install:
branches:
  only:
    - master
    - /^greenkeeper-.*$/
after_success:
  - istanbul cover ./node_modules/mocha/bin/_mocha
  - bash <(curl -s https://codecov.io/bash)
